[package]
name = "nexa-labs"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nexa-domain = { path = "../nexa-domain" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
uuid.workspace = true
